language: node_js
node_js:
  - '0.10'
before_script:
  - npm install gulp jspm
  - npm install
  - jspm install
script: gulp dist
deploy:
  provider: heroku
  app: showmewhatisaid
  api_key: "104e8799b11c9e206971b2062dfba87ba8380173"